### ISSUE TITLE
Bug report: SSL error

### ISSUE THREAD

**Issue by eugbyte** [nagyesta/lowkey-vault#230]
#### Describe the bug
SSL error when trying to ping the `https://localhost:8443`

#### To reproduce

```
$ curl https://localhost:8443
curl: (60) SSL certificate problem: self signed certificate
```

#### Expected behavior

No SSL error.

Alternatively, switch to http instead of https

#### Actual behavior
SSL error

#### A minimal project that can be used to reproduce the issue

If applicable. Please do NOT share sensitive information.

#### Environment

- OS: [e.g. Windows]

**Comment by nagyesta** [comment]
Thank you @eugbyte ! I have prioritized higher the related card on the roadmap: #231 
I think you might be facing an authentication issue, but will figure it out over the weekend and let you know.

**Comment by eugbyte** [comment]
Thanks for your help ! 🙏 I think when using the `Go` sdk, it probably encountered an SSL error when making a call to `https://localhost:8443/...`

**Comment by nagyesta** [comment]
Hi @eugbyte ,
#231 is resolved. Please find the example project here: https://github.com/nagyesta/lowkey-vault-example-go

I think you were missing the following two things:

## A fake authentication credential

This is necessary to avoid going to the real Azure authentication endpoints.

https://github.com/nagyesta/lowkey-vault-example-go/blob/b1c2472b9c422080d9f7d0fc6d4a2b426ac4b59f/src/lowkey-vault-example_test.go#L110-L115

## An override to accept the self-signed certificate

As far as I know, this is setting up a HTTP client:

https://github.com/nagyesta/lowkey-vault-example-go/blob/b1c2472b9c422080d9f7d0fc6d4a2b426ac4b59f/src/lowkey-vault-example_test.go#L92-L96

Then this can tell the Azure client to use it for secrets:

https://github.com/nagyesta/lowkey-vault-example-go/blob/b1c2472b9c422080d9f7d0fc6d4a2b426ac4b59f/src/lowkey-vault-example_test.go#L26-L28

And this will do the same for keys:

https://github.com/nagyesta/lowkey-vault-example-go/blob/b1c2472b9c422080d9f7d0fc6d4a2b426ac4b59f/src/lowkey-vault-example_test.go#L55-L57

Please let me know how it went!

**Comment by eugbyte** [comment]
It works!

Is it possible to shift the `prepareClient()` and `GetToken()` functions to the main file, so that users will better know how to set up? E.g.
```
// FakeCredential and prepareClient already imported in the same file
         var client *azsecrets.Client
          if os.Getenv("stage") == "dev" {
		httpClient := prepareClient()
		client = azsecrets.NewClient("https://localhost:8443",
			&FakeCredential{},
			&policy.ClientOptions{Transport: &httpClient})
		return &vs
	} else {
	    credential, err := azidentity.NewDefaultAzureCredential(nil)
	    client = azsecrets.NewClient(vaultURI, credential, nil)
	}
```

**Comment by nagyesta** [comment]
Thank you for letting me know @eugbyte ! I think I got what you mean. 

Originally, the example(s) I have provided are covering the same situation in all languages (Java, .Net, Python, Go) simulating that you have an app where you intend to use the real Azure Key Vault in production, but you want to replace it with a test double (e.g. Lowkey Vault). If you are doing so, I would assume it is better not adding test specific/test only dependencies or "hacks" into the production code, because it would add an additional possibility for failure and it would weaken security (for example accepting self-signed certs in production is not a good idea in general.
Due to this, the fake authentication specific and the cert specific parts were added to the test code only, to avoid giving bad advice to people who are not necessarily knowing why the examples look like they do. Basically to err on the safe side.

With that said, the approach you have shared can work, please feel free to use it (since you know why are you doing it)!

I think, I will need to add additional docs to all example projects anyway to make them easier to use and understand, I will try to highlight these nuances and give more pointers to people to figure out what custom solutions would need.

All in all, thank you for the feedback, these remarks will help make things better on the long run (as soon as I have time to document/update stuff)!

Since your issue is solved, I am closing this ticket, but please feel free to reach out either in a discussion or in an issue, happy to hear how the project could improve!
