### ISSUE TITLE
Howto get connection working with a non standard ip address 

### ISSUE THREAD

**Issue by espenfossen** [nagyesta/lowkey-vault#300]
#### Question

I have som Junit5 tests running fine on my local machine, but I am trying to get the builds running on Jenkins. Jenkins is running containers on a dedicated IP address (10.1.0.1) which is not 127.0.0.1, and I don´t have access to modifying the hosts file to add any aliases. So I have been fiddeling around with a lot of different settings to try to get this working, but I am always ending up with the follow error:

`
Error during creation of vault: Certificate for <10.1.0.1> doesn't match any of the subject alternative names: [lowkey-vault.local, lowkey-vault, *.localhost, *.lowkey-vault, *.lowkey-vault.local, *.default.svc.cluster.local, localhost, 127.0.0.1]
`

If I modify ApacheHttpClient#ApacheHttpClient with the following

`                        TrustStrategy acceptingTrustStrategy = (cert, authType) -> true;
            builder.loadTrustMaterial(null, acceptingTrustStrategy);
            SSLContext build = builder.loadTrustMaterial(new TrustAll()).build();
            final SSLConnectionSocketFactory socketFactory = new SSLConnectionSocketFactory(build,        SSLConnectionSocketFactory.ALLOW_ALL_HOSTNAME_VERIFIER);
`
to access any cerificate/hostname it starts working, but I really want to try to get it running with the built in lowkey-client. 

Maybe I am trying to use Lowkey in the wrong way, but to get this working it seems I need to create an vault with the URI https://10.1.0.1:30443.

Is there any way to make the initial vault, without using .importFile() create with the vault URI like https://10.1.0.1:30443 ?

**Comment by nagyesta** [comment]
Hi @espenfossen ,
thank you for using Lowkey Vault! Also, thank you for asking a great question! From what you have shared, I assume you are using both the Lowkey Vault Testcontainers module and the Lowkey Vault Client as well in your tests. Please let me know if this is not the case!

Based on what I have understood your setup looks similar to this on Jenkins:

```mermaid
  C4Deployment
    Deployment_Node(agent, "Jenkins Agent", "127.0.0.1"){
        Deployment_Node(host, "Jenkins container host", "10.1.0.1"){
            Container(sut, "System under test", "App being tested", "https://10.1.0.1:30243/")
            Container(lv, "Lowkey Vault", "AKV test double", "https://10.1.0.1:30443/")
        }
        Container(tests, "JUnit5", "Tests", "The tests you are executing.")
    }


    Rel(tests, sut, "Makes test calls", "HTTPS")
    Rel(sut, lv, "Uses Vault", "HTTPS")
    Rel(tests, lv, "Sets up Vault content", "HTTPS")
    
    UpdateRelStyle(tests, sut, $offsetX="-40", $offsetY="20")
    UpdateRelStyle(sut, lv, $offsetX="-20", $offsetY="20")
    UpdateRelStyle(tests, lv, $offsetY="40", $offsetX="50")
```

If this is accurate, then both your tests and your system under test can reach the Lowkey Vault container port using the same `https://10.1.0.1:30443/` address. As you have already seen, unfortunately the default certificate does not cover this domain, therefore you are facing the issues you have described.

If my above assumptions are correct, then your situation is not as bad as it first looks, as the client should be perfectly capable of solving the problem you are facing thanks to the built-in [host authority override feature](https://github.com/nagyesta/lowkey-vault/wiki/Example:-How-can-you-use-Lowkey-Vault-in-your-tests#4-using-multiple-subdomains-optional). This feature is basically overriding the [`Host` header](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Host) with a custom value you can define. Since the header is not used in the actual IP routing, it does not matter whether your hosts files would really resolve the domain you are sending to 10.1.0.1 or not. Same thing is true for the port as well. Thanks to this, you can simply tell the client that whenever you are asking it to send a request to `https://localhost:8443` (the default vault URL which is one of the auto-registered vaults and is covered by the default certificate as well), then it should actually send it to `10.1.0.1:30443` and set the host header value to `localnost:8443`. This should allow you to pass host validation and use the self-signed certificate.

In order to properly set the host authority override when you are creating your client, you should do something like this:

```java
final AuthorityOverrideFunction authorityOverrideFunction = new AuthorityOverrideFunction(
    //the logical vault URL we want to use to select the right vault inside Lowkey Vault                
    //this will be used during host name verification as well
    "localhost:8443",
    //the address where the packets will be sent
    "10.1.0.1:30443"
); 
final KeyClient keyClient = new ApacheHttpClientProvider(
    //the logical vault URL we want to use to select the right vault inside Lowkey Vault                
    "localhost:8443", 
    //the override function we have just set up
    authorityOverrideFunction
).getKeyClient();
```

You can check this test as well, although it is using a lower level API to do the same: https://github.com/nagyesta/lowkey-vault/blob/main/lowkey-vault-testcontainers/src/test/java/com/github/nagyesta/lowkeyvault/testcontainers/LowkeyVaultContainerJupiterTest.java

Also, as proof of concept, the same host authority override trick is used in our tests which are using dozens of made up URLs for selecting the different vaults inside the single Docker instance:
https://github.com/nagyesta/lowkey-vault/blob/fb75496c6b0d118f36aee2f57753f69e5e8d2b91/lowkey-vault-docker/src/test/java/com/github/nagyesta/lowkeyvault/steps/KeysStepDefs.java#L48-L54

I hope these example will help, but please let me know how it goes!

**Comment by nagyesta** [comment]
Hi @espenfossen ,
I have just realized how wrong I was in my previous response! Terribly sorry in case I have lead you to more unnecessary investigation. Although the authority override function is replacing the header, the host name verification will check the original name. Please disregard what I have written, I will add a way to turn off the host verification as you suggested.

**Comment by nagyesta** [comment]
Hi @espenfossen ,
I have released some improvements in `v1.13.0`:
- The constructor of the `ApacheHttpClient` accepts `TrustStrategy` and `HostnameVerifier` parameters now, so you can easily turn off SSL checks if necessary.
- Also, the new version of the Testcontainers module should make it easier to use a custom key store for HTTPS traffic, therefore, you should be able to even use your own certificate matching the domain/IP you need for your tests.

I hope these new options will help solve your issue! Apologies for my mistake earlier and looking forward to your feedback!

**Comment by espenfossen** [comment]
Great work. Now my tests are running on the Jenkins server without issues.

**Comment by nagyesta** [comment]
Great, thank you!
