### ISSUE TITLE
Attempting to connect to non-default vault fails

### ISSUE THREAD

**Issue by mcolebiltd** [nagyesta/lowkey-vault#819]
I am attempting to create ephemeral vaults to use with automatic tests using .NET. Everything works fine when connecting to the default clients at `https://localhost:8443`. When I create a new client, I am unable to connect to it and get an error: "No such host is known". I even tried to connect to `https://primary.localhost:8443` but still get the same error. I know I'm probably just missing something silly. How can I create two clients in parallel that point to different key vaults? Thanks!

**Comment by nagyesta** [comment]
Hi @mcolebiltd ,
thank you for using Lowkey Vault, and thank you for opening this question!
From your description, it looks like your OS layer is the one kindly informing you about the fact that the host using the `primary.localhost` name is unknown. You can solve this issue in at least a few ways:

1. If you can add the `primary.localhost` name as `127.0.0.1` to your hosts file, that should get rid of the error.
2. Or, you could try using the `https://127.0.0.1:8443` as the second vault (it is a completely different vault than `https://localhost:8443`).
3. Or, you can use the [alias feature](https://github.com/nagyesta/lowkey-vault/blob/main/lowkey-vault-app/README.md#defining-vault-aliases-for-auto-registered-vaults) to set your real IP address and port number as the alias of any of the vaults, so that you can reach them using your IP.
4. Otherwise, you need to somehow convince your network to send the packets to Lowkey Vault while using the `primary.localhost:8443` value as host header, so that the app will be able to find which vault it should use. As this is the hardest, I would recommend to try the other 3 options first.

Please let me know how it goes and whether this was helpful! Thank you!

**Comment by mcolebiltd** [comment]
Option 2 worked like a charm. Thank you!

**Comment by nagyesta** [comment]
Hi, thank you for letting me know! Best of luck!
